version: "3.6"
services:
  web:
    build: .
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine" 
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./redisdata:/data
